### PR TITLE
Photo gallery update

### PR DESCRIPTION
**Pull request by redwan-a**
Inserted links:
Chinese New Year Celebrations (Jan 20)
Primary 1's First Day (Jan 3)

### CODE REVIEW

**Comment by chuaboonli1972** [comment]
ok

**Comment by chuaboonli1972** [comment]
yes

**Comment by chuaboonli1972** [comment]
ok

**Comment by chuaboonli1972** [comment]
ok

**Comment by chuaboonli1972** [comment]
ok

**Review by JaniceTCP — APPROVED** [review]
All good.

**Pull request merged**
